import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Work_Sans } from "next/font/google";
import { ContextProvider } from "@/contexts/ContextProvider";

const workSans = Work_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.className}`}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
